#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'
sed -i '/^\tserver_name _.*/a \\trewrite ^/redirect_me https://github.com/RealLionelMuhire permanent;' /etc/nginx/sites-available/default
service nginx restart
