#!/usr/bin/env bash
# Updating package information and then installing Nginx with yes
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# starting nginx
service nginx start

