#!/usr/bin/env bash
# Update package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Define the HAProxy configuration
server_config=\
"
frontend sylvieshimwauwase_frontend
    bind *:80
    mode http
    default_backend sylvieshimwauwase_backend

backend sylvieshimwauwase_backend
    balance roundrobin
    mode http
    server 76023-web-01 3.84.161.50:80 check
    server 76023-web-02 100.25.131.191:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
