#!/usr/bin/env bash
# Update package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Define the HAProxy configuration
server_config=\
"
frontend lionelmuhire_frontend
    bind *:80
    mode http
    default_backend lionelmuhire_backend
    timeout client 30s
    timeout connect 5s
    timeout server 30s

backend lionelmuhire_backend
    balance roundrobin
    mode http
    server 76023-web-01 3.84.161.50:80 check
    server 76023-web-02 100.25.131.191:80 check
    timeout client 30s 
    timeout connect 5s
    timeout server 30s
"
# Overwrite the HAProxy configuration file instead of appending
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Check the HAProxy configuration and restart HAProxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg && sudo service haproxy restart

