#!/usr/bin/env bash
#creating an adv 
mkdir -p var/run
touch var/run/myscript.pid
echo "$(pgrep -f ./100-process_and_pid_file)" > /var/run/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' & rm -f /var/run/myscript.pid & exit" SIGTERM
trap "rm -f /var/run/myscript.pid & exit" SIGQUIT

while((1))
do
	echo "To infinity and beyond"
	sleep 2
done
