#!/usr/bin/env bash
#Best School and chances from italy japan and china
i=1
while ((i <= 20))
do
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
