#!/usr/bin/env bash
#checking the existance of a file
filename="school"
if [ -e $filename ]; then
	echo "school file exists"
	if [ -s $filename ]; then
		echo "school file is not empty"
		if [ -f $filename ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
		if [ -f $filename ]; then
                        echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
